spring.application.name=TP2

# --- CONEXIÓN CON MYSQL (DOCKER) ---
# localhost:3306 es el puerto expuesto de Docker.
# sistema_bancario es el nombre de la base de datos creada.
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_bancario?useSSL=false&serverTimezone=America/Argentina/Jujuy&allowPublicKeyRetrieval=true
spring.datasource.username=admin_banco
spring.datasource.password=daas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURACIÓN DE HIBERNATE (JPA) ---
# 'update': examina tus clases @Entity y si las tablas no existen en MySQL, las crea automáticamente.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de tu IDE los comandos SQL reales (CREATE TABLE, INSERT, etc.)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true